package com.atguigu.cfx.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2017-05-27T22:50:14.516+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://test.cfx.atguigu.com/", name = "HelloWorld")
public interface HelloWorld {

    @WebResult(name = "sayHelloReturn", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://test.cfx.atguigu.com/", className = "com.atguigu.cfx.test.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://test.cfx.atguigu.com/", className = "com.atguigu.cfx.test.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(name = "age", targetNamespace = "")
        int age
    );
}
